---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-xml
      - id: check-yaml
  - repo: local
    hooks:
      - id: vala-lint
        name: vala-lint
        description: This hook runs vala-lint.
        entry: io.elementary.vala-lint -c .vala-lint.ini
        language: system
        files: \.vala$
      - id: ninja
        name: ninja
        description: This runs ninja
        entry: bash -c 'current_dir=$PWD && cd build && ninja && cd $current_dir'
        language: system
        files: \.vala$
